name: "Trần Xuân Nam"
account: "@namtx"
title: "Ruby Developer / Javascript lover"
description: Blogging about stuffs what I learned
meta_description: "Trần Xuân Nam, Blogging about stuffs what I learned"
facebook: "https://fb.com/mysm.xuannam"
github: "https://github.com/namtx"
twitter: "https://twitter.com/nam___tx"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'namtx.github.io'
google_analytics: 'UA-103273269-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://namtx.github.io'
author:         '0x6e616d7478'
